language: node_js
node_js:
  - stable
branches:
  only:
    - master
    - develop
install:
  - npm install -g @angular/cli
script:
  - mkdir animations-lib
  - mv *.json animations-lib
  - mv README.md animations-lib
  - mv jest.config.js animations-lib
  - mv src animations-lib
  - ng new build-lib-app --createApplication=false --routing=false --style=scss
  - cd build-lib-app
  - ng generate library animations-lib
  - rm -rf projects/animations-lib/
  - mv ../animations-lib/ projects/
  - ng build animations-lib
  - cd dist/libs/animations-lib/
deploy:
  provider: npm
  email: servrox@live.com
  api_key:
    secure: kKhxXMQIezp6mGWsMJhod7hFnU9VbQyPf1lt+zGBG06ijfDGl+7I0fqGBnvTt5Ze2G0oJfnsFzhOXlzlJJudASPseO1Bmswh3T9h8nLNkgC71a7u5qCEx3QBDHbLTK8jCF+QuXF+/qdpGpiT/ChMoqNduhJn09pvBtqapWXt4ZImCU0GFjnTRWNM5Nyr3iruZRdEyaG7/GrZWDveg7g92T0EYL935sgjcrEBo/ssgtWQ0A/aWA5FH5tgycDfzx+N9sM487MGZTeukoEPrHx22+bngbdlTfxyHGyKGJ1l24ZR6gp0ctIhiWksjv6NoaK29HC/O7oG7GBw72fKBzydG1FJPUZz3QgJQqcFaSl4zPbb67Y5R73obQ5SrHrIuyjqTfzuX0LeWNyaVPVdNpMZ0OjXb8Fv8omsSQUKp7BavtsxJSm9DPO25IN6vLAgdQsPNkSk4UI9Z83yqIZK62RyteVSvgVHhunnKyqInkgMT/BXD8N58iu8RjdbMiiOPHEKQr1nRZMoXsUF2opBMyO9SzyvTVrj1Od4vewpq/3W1HFNws39PqWbUpSgNfeUAGhCFOne28ahggMU+a3VOeSks1B7qhKEkRKZS0avhDNIjua6mReerg1QCL9lk6HKNAibxKNKYrcvwGN1WGsQ3phhaiMA5gKRulQrPrd9Ja/MUzo=
  on:
    repo: servrox/animations-lib
